# Generated by Django 5.1.1 on 2025-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaContratista',
            fields=[
                ('id_emp_con', models.AutoField(db_comment='\r\nID EMPRESA CONTRATISTA', primary_key=True, serialize=False)),
                ('rut_emp_con', models.CharField(db_comment='RUT EMPRESA CONTRATISTA', max_length=25, unique=True)),
                ('nombre_emp_con', models.CharField(db_comment='NOMBRE EMEPRESA CONTRATISTA', max_length=255)),
                ('correo_emp_con', models.CharField(db_comment='CORREO EMPRESA CONTRATISTA', max_length=255)),
                ('status_emp_con', models.IntegerField(db_comment='0 DESACTIVADO\r\n1 ACTIVADO')),
            ],
            options={
                'db_table': 'empresa_contratista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaPrincipal',
            fields=[
                ('id_emp_pri', models.AutoField(db_comment='ID Empresa Principal', primary_key=True, serialize=False)),
                ('rut_emp_pri', models.CharField(db_comment='RUT EMPRESA Principal', max_length=25, unique=True)),
                ('nombre_emp_pri', models.CharField(db_comment='NOMBRE EMPRESA PRINCIPAL', max_length=255)),
                ('correo_emp_pri', models.CharField(db_comment='CORREO EMPRESA PRINCIPAL', max_length=255)),
                ('status_emp_pri', models.IntegerField(db_comment='0 DESACTIVADA\r\n1 ACTIVADA')),
            ],
            options={
                'db_table': 'empresa_principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaSubcontratista',
            fields=[
                ('id_emp_subcon', models.AutoField(db_comment='ID EMPRESA SUBCONTRATISTA', primary_key=True, serialize=False)),
                ('rut_emp_subcon', models.CharField(db_comment='RUT EMPRESA SUBCONTRATISTA', max_length=25, unique=True)),
                ('nombre_emp_subcon', models.CharField(db_comment='NOMBRE EMPRESA SUBCONTRATISTA', max_length=255)),
                ('correo_emp_subcon', models.CharField(db_comment='CORREO EMPRESA SUBCONTRATISTA', max_length=255)),
                ('status_emp_subcon', models.IntegerField(db_comment='0 DESACTIVADO\r\n1 ACTIVADO')),
            ],
            options={
                'db_table': 'empresa_subcontratista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresasUnidas',
            fields=[
                ('id_emp_uni', models.AutoField(db_comment='ID EMPRESAS UNIDAS', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empresas_unidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(db_comment='ID PERIODO', primary_key=True, serialize=False)),
                ('mesanio_periodo', models.IntegerField(db_comment='ANIO Y MES EJEM 202404')),
                ('minimo_imponible_periodo', models.IntegerField(db_comment='MINIMO IMPONIBLE POR PERIODOS')),
                ('maximo_imponible_periodo', models.IntegerField(db_comment='MAXIMO IMPONIBLE POR PERIODOS')),
                ('status_periodo', models.IntegerField(db_comment='0 DESACTIVADO\r\n1 ACTIVADO')),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_sol', models.AutoField(db_comment='ID SOLICITUD', primary_key=True, serialize=False)),
                ('nombre_contrato_sol', models.CharField(db_comment='NOMBRE CONTRATO PROYECTO SOLICITUD', max_length=255)),
                ('cant_trab_acreditar_sol', models.IntegerField(db_comment='CANTIDAD TRABAJADORES CERTIFICAR SOLICITUD')),
                ('total_trab_sol', models.IntegerField(db_comment='CANTIDAD TOTALES DE LA EMPRESA ')),
                ('estado_certificacion_sol', models.CharField(db_comment='ESTADO CERTIFICACION', max_length=14)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id_trabajador', models.AutoField(db_comment='ID TRABAJADOR', primary_key=True, serialize=False)),
                ('rut_trabajador', models.CharField(db_comment='RUT TRABAJADOR', max_length=25)),
                ('nombre_trabajador', models.CharField(db_comment='NOMBRE TRABAJADOR', max_length=25)),
                ('apaterno_trabajador', models.CharField(db_comment='APELLIDO PATERNO TRABAJADOR', max_length=25)),
                ('amaterno_trabajador', models.CharField(db_comment='APELLIDO MATERNO TRABAJADOR', max_length=25)),
            ],
            options={
                'db_table': 'trabajadores',
                'managed': False,
            },
        ),
    ]
